plugins {
    id "com.gradleup.shadow" version "9.6.1"
    id "io.freefair.lombok" version "9.5.0"
}

apply plugin: 'java'
version = '1.0.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

shadowJar {
    filesMatching('META-INF/*.kotlin_module') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    mergeServiceFiles()
    filesMatching('META-INF/services/**') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'net.nextinfinity.timerbot.TimerBot'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.dv8tion:JDA:6.6.0'
    implementation 'org.reflections:reflections:0.10.2'

    runtimeOnly 'org.slf4j:slf4j-reload4j:2.0.19'
}
